/* noteHtmlRender.test.ts — rewriteNoteLinks / generateNoteToc against REAL
   LazyBrain engine output formats.

   The formats pinned here were confirmed by running the engine's own
   `index-rebuild` + `graph` + `build-index` + `build-hierarchy` pipeline
   against a disposable test brain (copied real notes + a real code-scan)
   and reading the generated note HTML back — not guessed from reading the
   composer source alone. Two things that static reading would miss:

   1. The engine is NOT consistent about how it encodes note ids in href
      attributes across composers: wikilinks.ts / interlink.ts / template.ts
      call encodeURIComponent(id) for the `#/note/<id>` format, but
      hierarchy-node-composer.ts uses esc() (HTML-escaping only) for the
      exact same `#/note/<id>` format. rewriteNoteLinks must tolerate both.
   2. The single most common real link shape (auto-linker "mentions" links
      via engine/src/graph/entities.ts applyAutoLinks, and "[source]"
      conversation-provenance links on fused Decisions/Bugs/Ideas/Rules/QA
      items) is a BARE `#<id>` fragment with no leading slash — the exact
      same syntax as a genuine same-page anchor (`#see-also`, `#fn-*`).
      rewriteNoteLinks intentionally leaves these untouched; WikiPage
      disambiguates them at click time via DOM lookup (see WikiPage.test.tsx). */

import { describe, it, expect } from 'vitest';
import { rewriteNoteLinks, generateNoteToc } from '../components/brain/noteHtmlRender';

describe('rewriteNoteLinks — real engine link formats', () => {
  it('keeps #/wiki/<id> unchanged and marks it as a wiki-link', () => {
    const html = '<a href="#/wiki/some-id">Some note</a>';
    const out = rewriteNoteLinks(html);
    expect(out).toContain('href="#/wiki/some-id"');
    expect(out).toContain('wiki-link');
  });

  it('rewrites an encodeURIComponent-encoded #/note/<id> (wikilinks.ts format) to #/wiki/<id>, round-tripping a colon id', () => {
    // engine/src/annotator/wikilinks.ts:
    //   anchor.setAttribute('href', `#/note/${encodeURIComponent(resolved.id)}`);
    const html = '<a href="#/note/file%3Asrc%2Ffoo.ts">foo.ts</a>';
    const out = rewriteNoteLinks(html);
    expect(out).toContain(`href="#/wiki/${encodeURIComponent('file:src/foo.ts')}"`);
  });

  it('rewrites a raw (non-URL-encoded) #/note/<id> with a colon (hierarchy-node-composer.ts format) the same way', () => {
    // engine/src/commands/hierarchy-node-composer.ts uses esc() (HTML-escape
    // only, no URL-encoding): `href="#/note/${esc(d.sourceId)}"`. The engine
    // is inconsistent here across composers; rewriteNoteLinks must still
    // resolve to the same canonical #/wiki/<id> target either way.
    const html = '<a href="#/note/file:src/foo.ts">source</a>';
    const out = rewriteNoteLinks(html);
    expect(out).toContain(`href="#/wiki/${encodeURIComponent('file:src/foo.ts')}"`);
  });

  it('leaves #/file:<path> untouched but tags it with data-file-path (intentional: opens in the code editor, not the note)', () => {
    // Real generated import link, confirmed via a live test-brain code-scan
    // (engine/src/annotator/blocks/composers/file-neuron.ts):
    //   <a href="#/file:../annotator/heuristic.js"><code>../annotator/heuristic.js</code></a>
    const html = '<a href="#/file:../annotator/heuristic.js">../annotator/heuristic.js</a>';
    const out = rewriteNoteLinks(html);
    expect(out).toContain('href="#/file:../annotator/heuristic.js"');
    expect(out).toContain('data-file-path="../annotator/heuristic.js"');
  });

  it('leaves a bare #<id> mentions auto-link untouched (no rewrite, no wiki-link class)', () => {
    // Real link freshly generated by running `lazybrain graph` on a
    // disposable test brain (engine/src/graph/entities.ts applyAutoLinks):
    //   <a href="#learning-retirer-les-mentions-github-du-copy-closed-source-2026-07-07"
    //      data-cerveau-link-type="mentions" data-cerveau-link-confidence="inferred"
    //      data-cerveau-link-auto="1">Agent</a>
    // Confirmed present in ~97% of notes in a real archived brain.
    const html =
      '<a href="#learning-retirer-les-mentions-github-du-copy-closed-source-2026-07-07" ' +
      'data-cerveau-link-type="mentions" data-cerveau-link-auto="1">Agent</a>';
    const out = rewriteNoteLinks(html);
    expect(out).toContain(
      'href="#learning-retirer-les-mentions-github-du-copy-closed-source-2026-07-07"',
    );
    expect(out).not.toContain('wiki-link');
  });

  it('leaves a "[source]" conversation-provenance bare-hash link untouched', () => {
    // Real format seen throughout Decisions/Bugs/Ideas/Rules sections of
    // hierarchy/aggregate notes in a real archived brain.
    const html =
      '<li>Some decision text <a href="#2026-06-08-claude-cli-besoin-d-un-coupe-circuit-e63a1f47" ' +
      'class="conv-source">[source]</a></li>';
    const out = rewriteNoteLinks(html);
    expect(out).toContain('href="#2026-06-08-claude-cli-besoin-d-un-coupe-circuit-e63a1f47"');
  });

  it('rewrites a bare #<id-with-colon> (legacy neuron reference) to #/wiki/<id>', () => {
    const html = '<a href="#concept:auth-decision">auth decision</a>';
    const out = rewriteNoteLinks(html);
    expect(out).toContain(`href="#/wiki/${encodeURIComponent('concept:auth-decision')}"`);
  });

  it('keeps a see-also / related #/<id> link\'s href unchanged (routed via topic->note fallback, not rewritten here)', () => {
    // engine/src/annotator/blocks/see-also.ts: `href="#/${l.id}"`
    const html = '<a href="#/abc-123" class="section-link">Related</a>';
    const out = rewriteNoteLinks(html);
    expect(out).toContain('href="#/abc-123"');
    expect(out).toContain('wiki-link');
  });

  it('leaves in-page symbol anchors (#fn-*/#cls-*) fully untouched', () => {
    const html = '<a href="#fn-runDream">runDream</a>';
    const out = rewriteNoteLinks(html);
    expect(out).toBe(html);
  });
});

describe('generateNoteToc', () => {
  it('returns null for fewer than 2 headings', () => {
    expect(generateNoteToc('<h2>Only one</h2>')).toBeNull();
  });

  it('builds a TOC with ids for 2+ h2/h3 headings, matching real section names', () => {
    const html = '<h2>Architecture</h2><p>...</p><h2>See also</h2>';
    const out = generateNoteToc(html);
    expect(out).not.toBeNull();
    expect(out as string).toContain('class="toc"');
    expect(out as string).toContain('href="#architecture"');
    expect(out as string).toContain('href="#see-also"');
  });
});
