import { existsSync, mkdirSync, readFileSync, statSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { parseHTML } from 'linkedom';
import { type NoteFile, readAllNotes } from '../store/reader.js';
import { getConfig } from '../util/config.js';

export interface BacklinkEntry {
  from: string; // source note id
  to: string; // target note id
  type: string; // mentions | refines | contradicts | …
  auto: boolean; // generated by auto-linker?
  surface?: string; // visible link text
  confidence: 'extracted' | 'inferred' | 'ambiguous';
  confidenceScore: number;
}

export interface BacklinksIndex {
  outgoing: Record<string, BacklinkEntry[]>; // id -> outgoing edges
  incoming: Record<string, BacklinkEntry[]>; // id -> incoming edges
  generated: string; // ISO timestamp
  total_edges: number;
}

const BACKLINKS_FILENAME = 'backlinks.json';

export function buildBacklinks(notes?: NoteFile[]): BacklinksIndex {
  const all = notes ?? readAllNotes();
  // Build a set of known note ids for defensive validation.
  // Edges whose target does not exist in the corpus are dropped to prevent
  // ghost hub nodes caused by stale links or renamed notes.
  const knownIds = new Set(all.map((n) => n.id).filter(Boolean));

  const outgoing: Record<string, BacklinkEntry[]> = {};
  const incoming: Record<string, BacklinkEntry[]> = {};
  let total = 0;

  for (const note of all) {
    if (!note.id) continue;
    const { document } = parseHTML(`<!doctype html><html><body>${note.html}</body></html>`);
    const root = document.body || document.documentElement;
    if (!root) continue;
    const anchors = Array.from(root.querySelectorAll('a[href]'));
    for (const a of anchors) {
      const href = a.getAttribute('href') ?? '';
      const targetId = parseTargetId(href);
      // Drop self-links, unresolvable hrefs, and edges whose target is not in
      // the known note set (ghost notes / stale links / in-page nav anchors
      // that slipped through any future parser change).
      if (!targetId || targetId === note.id) continue;
      if (!knownIds.has(targetId)) continue;
      const autoFlag = a.getAttribute('data-cerveau-link-auto') === '1';
      const confAttr = a.getAttribute('data-cerveau-link-confidence') as
        | 'extracted'
        | 'inferred'
        | 'ambiguous'
        | null;
      const confidence = confAttr ?? (autoFlag ? 'inferred' : 'extracted');
      const confidenceScore =
        confidence === 'extracted' ? 1.0 : confidence === 'inferred' ? 0.5 : 0.2;
      const entry: BacklinkEntry = {
        from: note.id,
        to: targetId,
        type: a.getAttribute('data-cerveau-link-type') ?? 'link',
        auto: autoFlag,
        surface: (a.textContent ?? '').trim().slice(0, 120) || undefined,
        confidence,
        confidenceScore,
      };
      if (!outgoing[note.id]) outgoing[note.id] = [];
      outgoing[note.id].push(entry);
      if (!incoming[targetId]) incoming[targetId] = [];
      incoming[targetId].push(entry);
      total += 1;
    }
  }

  return {
    outgoing,
    incoming,
    generated: new Date().toISOString(),
    total_edges: total,
  };
}

/**
 * In-process cache for loadBacklinks() — see corpus-cache.ts's module doc for
 * the sibling design this mirrors. backlinks.json is a plain file (not a
 * SQLite table), so freshness is gated on (path, mtimeMs, size) instead of
 * PRAGMA data_version: any rewrite of the file — by this process
 * (saveBacklinks) or a separate `lazybrain graph`/index-rebuild process —
 * changes mtimeMs, which invalidates the entry on the next loadBacklinks()
 * call. `path` is folded in so switching brains (different cachePath) never
 * serves a stale entry from a previous brain.
 *
 * Measured impact: on a realistic 5488-note brain, backlinks.json is ~44 MB;
 * readFileSync + JSON.parse costs ~300-590ms PER CALL. loadBacklinks() is
 * called from router.ts's hydrateHits() on every route(..., hydrateNote:true)
 * request (i.e. nearly every assistant turn via inject-context.ts) AND from
 * pagerank.ts's computePageRank() on every PageRank cache miss — both hot
 * paths that used to pay this cost repeatedly per query with nothing on disk
 * having changed.
 */
let cachedBacklinks: { path: string; mtimeMs: number; size: number; value: BacklinksIndex } | null =
  null;

export function saveBacklinks(idx: BacklinksIndex): string {
  const cfg = getConfig();
  if (!existsSync(cfg.cachePath)) mkdirSync(cfg.cachePath, { recursive: true });
  const path = join(cfg.cachePath, BACKLINKS_FILENAME);
  writeFileSync(path, JSON.stringify(idx, null, 2), 'utf8');
  // Seed the cache with what we just wrote instead of merely invalidating —
  // a loadBacklinks() call immediately after a rebuild (common: the CLI that
  // just called saveBacklinks often calls loadBacklinks() next) is served
  // from memory instead of re-reading the file it just wrote.
  try {
    const stats = statSync(path);
    cachedBacklinks = { path, mtimeMs: stats.mtimeMs, size: stats.size, value: idx };
  } catch {
    cachedBacklinks = null;
  }
  return path;
}

export function loadBacklinks(): BacklinksIndex | null {
  const cfg = getConfig();
  const path = join(cfg.cachePath, BACKLINKS_FILENAME);
  let stats: ReturnType<typeof statSync>;
  try {
    stats = statSync(path);
  } catch {
    return null;
  }
  if (
    cachedBacklinks &&
    cachedBacklinks.path === path &&
    cachedBacklinks.mtimeMs === stats.mtimeMs &&
    cachedBacklinks.size === stats.size
  ) {
    return cachedBacklinks.value;
  }
  try {
    const value = JSON.parse(readFileSync(path, 'utf8')) as BacklinksIndex;
    cachedBacklinks = { path, mtimeMs: stats.mtimeMs, size: stats.size, value };
    return value;
  } catch {
    cachedBacklinks = null;
    return null;
  }
}

/** Test-only: reset the in-process backlinks cache between tests. */
export function resetBacklinksCacheForTests(): void {
  cachedBacklinks = null;
}

/**
 * Extract the note id from an href attribute.
 *
 * Accepted inter-note link formats:
 *
 * 1. "#/note/<id>" and "#/wiki/<id>" — the explicit SPA-routable formats
 *    (see engine/examples/brain-ui/lib/router.js; the frontend's
 *    noteHtmlRender.ts rewrites the legacy "#/note/" form to "#/wiki/" on render).
 *
 * 2. Bare "#<id>" — the format the engine's OWN auto-linker emits
 *    (applyAutoLinks in entities.ts: `a.setAttribute('href', \`#${id}\`)`)
 *    and the format used by conv-source "[source]" provenance links
 *    (file-neuron.ts EnrichmentItem.sourceConvLink, e.g. "#conv-abc"). This
 *    is the DOMINANT link format across the corpus (~97% of notes) — the
 *    previous "#/note/"-only rule made buildBacklinks ignore almost every
 *    real link, so backlinks.json came out empty (backlinks_total: 0).
 *
 * All other fragment forms are in-page navigation anchors, NOT inter-note
 * links, and MUST be rejected:
 *   - "#fn-*" / "#cls-*" — file-neuron function/class symbol anchors.
 *   - "#/file:*"         — internal-import pseudo-links (renderArchitectureSection);
 *                          these resolve to a file path, never a note id.
 *   - any other "#/..."  — topic routes / stale directory breadcrumb paths.
 *   - bare heading/section anchors ("#see-also", "#children", "#architecture",
 *     "#decisions", TOC entries, etc.) use this SAME bare syntax as (2) above,
 *     so they cannot be told apart from a real note id by pattern alone. They
 *     are filtered out by the caller's `knownIds.has(targetId)` guard instead
 *     (a bare anchor name is never itself a real note id) — the same
 *     disambiguation the frontend performs at click time by checking whether
 *     an element with that id exists on the current page (see WikiPage.tsx
 *     handleArticleClick).
 *
 * File-derived fallbacks (e.g. "path.html" → "path") are intentionally never
 * supported: we never want implicit note resolution from arbitrary HTML links.
 */
function parseTargetId(href: string): string | null {
  if (!href.startsWith('#')) return null;

  // "#/note/<id>" and "#/wiki/<id>" — explicit SPA-routable note formats.
  const routedMatch = href.match(/^#\/(?:note|wiki)\/([a-z0-9_%-]+)$/i);
  if (routedMatch) return decodeTargetId(routedMatch[1]);

  // Any other "#/..." href is a different kind of route, not a note
  // reference: "#/file:<path>" (file-open pseudo-link) and "#/<dir>/<dir>"
  // (stale directory breadcrumb paths, topic filters) both land here.
  if (href.startsWith('#/')) return null;

  // Bare "#<id>" — accept as a candidate. In-page anchors (#see-also,
  // #children, #architecture, TOC entries, …) use this same syntax but are
  // filtered out downstream by the knownIds check. #fn-*/#cls-* are rejected
  // explicitly since they are always in-page symbol anchors, never note ids.
  const bareId = href.slice(1);
  if (!bareId || /^(fn|cls)-/i.test(bareId)) return null;
  if (!/^[a-z0-9_%-]+$/i.test(bareId)) return null;
  return decodeTargetId(bareId);
}

/** Decode percent-encoding that encodeURIComponent may have applied to an id. */
function decodeTargetId(raw: string): string {
  try {
    return decodeURIComponent(raw);
  } catch {
    return raw;
  }
}
