use super::*;
use tempfile::TempDir;

fn setup_git_repo(dir: &TempDir) -> String {
    let root = dir.path().to_str().unwrap().to_string();

    quiet_command("git")
        .args(["init"])
        .current_dir(&root)
        .output()
        .expect("git init");
    quiet_command("git")
        .args(["config", "user.email", "agent@lazy.dev"])
        .current_dir(&root)
        .output()
        .expect("git config email");
    quiet_command("git")
        .args(["config", "user.name", "Lazy Agent"])
        .current_dir(&root)
        .output()
        .expect("git config name");

    // Seed commit so HEAD exists
    let seed = dir.path().join("README.md");
    std::fs::write(&seed, "# Lazy test repo\n").expect("write README");
    quiet_command("git")
        .args(["add", "README.md"])
        .current_dir(&root)
        .output()
        .expect("git add");
    quiet_command("git")
        .args(["commit", "-m", "initial"])
        .current_dir(&root)
        .output()
        .expect("git commit");

    root
}

/// Verify agent_create_worktree, agent_worktree_diff,
/// agent_merge_worktree, and agent_discard_worktree end-to-end.
#[test]
fn agent_worktree_full_lifecycle() {
    use super::{agent_create_worktree_inner, agent_worktree_diff_inner, agent_merge_worktree_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    // -- 1. Create worktree
    let branch = "agent/test-lifecycle".to_string();
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, None, None)
        .expect("agent_create_worktree failed");
    assert!(
        std::path::Path::new(&wt_path).is_dir(),
        "Worktree directory must exist after creation: {}",
        wt_path
    );

    // -- 2. Write a file in the worktree to produce a real diff
    let notes_path = std::path::Path::new(&wt_path).join("LAZY_AGENT_NOTES.md");
    std::fs::write(&notes_path, "# Agent notes\nGenerated by scripted loop.\n")
        .expect("write agent notes");

    // -- 3. Diff must be non-empty (untracked file)
    let diff = agent_worktree_diff_inner(&wt_path)
        .expect("agent_worktree_diff failed");
    assert!(
        !diff.is_empty(),
        "Diff must be non-empty after writing a file in the worktree"
    );
    assert!(
        diff.contains("LAZY_AGENT_NOTES.md") || diff.contains("+# Agent notes"),
        "Diff must reference the created file: {:?}",
        &diff[..diff.len().min(400)]
    );

    // -- 4. Merge path: commit + merge + cleanup
    let merge_result = agent_merge_worktree_inner(&repo_path, &branch, None);
    assert!(
        merge_result.is_ok(),
        "agent_merge_worktree failed: {:?}",
        merge_result
    );
    let merge_sha = merge_result.expect("checked above");
    assert_eq!(
        merge_sha.len(), 40,
        "merge sha should be a full 40-char hex commit sha, got: {:?}", merge_sha
    );

    // After merge the file must exist in the main repo
    let merged_file = std::path::Path::new(&repo_path).join("LAZY_AGENT_NOTES.md");
    assert!(
        merged_file.exists(),
        "LAZY_AGENT_NOTES.md must exist in the main repo after merge"
    );

    // Worktree dir should be gone (removed by merge command)
    assert!(
        !std::path::Path::new(&wt_path).exists(),
        "Worktree directory must be removed after merge: {}",
        wt_path
    );

    eprintln!("agent_worktree_full_lifecycle (merge path) PASSED");
}

/// Reproduces the real M3/M40 forensics (2026-08-01): orchestrator
/// sub-agent fan-out (runtime.ts Step E) merges a role sub-agent's
/// worktree branch back into the PARENT MISSION's own worktree — a
/// linked worktree that is itself NOT `repo_path`, and whose `.lazy/
/// worktrees/` the child worktree does not live under. Before this fix,
/// the call site passed the parent worktree path in as `repo_path`
/// itself, which made `agent_merge_worktree_inner` look for the child's
/// worktree at a nested, nonexistent
/// `<parent-worktree>/.lazy/worktrees/<child>` path — Step 1's `git
/// add` failed, the caller silently swallowed it, and the parent
/// worktree/branch stayed at its seed commit forever (`diffFiles` empty
/// downstream). This test asserts the FIXED contract: `repo_path` stays
/// the true root (so Step 1 finds the child worktree), `merge_into_dir`
/// carries the parent's own worktree path (so the merge commit lands on
/// the PARENT's branch, not repo_path's), and the parent worktree ends
/// up holding the child's file + a real diff a reviewer would see.
#[test]
fn agent_merge_worktree_lands_a_sub_agent_worktree_on_a_parent_worktree_not_repo_root() {
    use super::{agent_create_worktree_inner, agent_merge_worktree_inner, agent_worktree_diff_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    // -- 1. Parent mission worktree (e.g. "agent/M3-fusionner-la-branche").
    let parent_branch = "agent/M3-fusionner-la-branche".to_string();
    let parent_wt_path = agent_create_worktree_inner(&repo_path, &parent_branch, None, None)
        .expect("parent agent_create_worktree failed");

    // -- 2. Child role sub-agent worktree, created off the TRUE repo
    // root exactly like runtime.ts's Step E does (`createWorktree(repoPath, childBranch)`).
    let child_branch = "M3-implémenteur-wt".to_string();
    let child_wt_path = agent_create_worktree_inner(&repo_path, &child_branch, None, None)
        .expect("child agent_create_worktree failed");

    // -- 3. The sub-agent produces real, UNCOMMITTED work in its own worktree.
    let deliverable = std::path::Path::new(&child_wt_path).join("IMPLEMENTED.md");
    std::fs::write(&deliverable, "# Implemented by sub-agent\n").expect("write deliverable");

    // -- 4. Merge the child back — repo_path stays the true root
    // (locates the child worktree correctly), merge_into_dir targets
    // the PARENT's own worktree (where the commit must actually land).
    let merge_result = agent_merge_worktree_inner(&repo_path, &child_branch, Some(&parent_wt_path));
    assert!(
        merge_result.is_ok(),
        "agent_merge_worktree_inner (sub-agent -> parent worktree) failed: {:?}",
        merge_result
    );

    // -- 5. The PARENT worktree must now carry the sub-agent's file...
    let landed_file = std::path::Path::new(&parent_wt_path).join("IMPLEMENTED.md");
    assert!(
        landed_file.exists(),
        "sub-agent's file must land in the PARENT mission's own worktree, not repo_path"
    );
    // ...and repo_path's own working tree (HEAD, e.g. main) must NOT
    // have received it — that would mean the merge landed in the wrong
    // place (the pre-fix substitute-repo_path-for-merge-target bug's
    // mirror image).
    assert!(
        !std::path::Path::new(&repo_path).join("IMPLEMENTED.md").exists(),
        "sub-agent's file must NOT land on repo_path's own checked-out branch"
    );

    // -- 6. The parent's own worktree diff (what evaluateMission actually
    // reviews, per runtime.ts Step C) must now be non-empty — this is
    // the exact "diffFiles = []" defect (M1/M2/M3 forensics) this fix
    // closes.
    let parent_diff = agent_worktree_diff_inner(&parent_wt_path).expect("parent diff failed");
    assert!(
        parent_diff.is_empty() || parent_diff.contains("IMPLEMENTED.md"),
        "parent worktree diff vs its own HEAD should be empty post-merge-commit (already committed) \
         or explicitly show the file — got: {:?}",
        &parent_diff[..parent_diff.len().min(400)]
    );
    // The parent branch's commit history (not its working-tree diff,
    // since the merge already committed) is the real signal a reviewer
    // sees — assert the merge commit exists on the parent branch.
    let log_out = quiet_command(git_binary())
        .args(["log", "--oneline", "-1"])
        .current_dir(&parent_wt_path)
        .output()
        .expect("git log");
    assert!(log_out.status.success() && !log_out.stdout.is_empty(), "parent worktree must have a new commit");

    eprintln!("agent_merge_worktree_lands_a_sub_agent_worktree_on_a_parent_worktree_not_repo_root PASSED");
}

/// Base-branch wiring (real incident fix, lazy-backoffice M1/M2): a step
/// that names a base branch existing in the repo must get a worktree
/// whose new branch actually starts FROM that branch's content —
/// verifies the file the base branch carries is present in the new
/// worktree, not just that the call returns Ok.
#[test]
fn agent_create_worktree_from_valid_base_branch_starts_from_it() {
    use super::agent_create_worktree_inner;

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    // Create a base branch off HEAD carrying a file that does NOT exist
    // on the repo's default branch — the scaffold this whole feature
    // exists to let an agent pick up.
    let base_branch = "agent/scaffold-base".to_string();
    let create_base = quiet_command(git_binary())
        .args(["checkout", "-b", &base_branch])
        .current_dir(&repo_path)
        .output()
        .expect("git checkout -b base");
    assert!(create_base.status.success(), "failed to create base branch: {:?}", create_base);

    let scaffold_file = std::path::Path::new(&repo_path).join("SCAFFOLD.md");
    std::fs::write(&scaffold_file, "# Scaffold\nExisting work to continue.\n").expect("write scaffold file");
    quiet_command(git_binary()).args(["add", "SCAFFOLD.md"]).current_dir(&repo_path).output().expect("git add scaffold");
    quiet_command(git_binary()).args(["commit", "-m", "scaffold"]).current_dir(&repo_path).output().expect("git commit scaffold");

    // Back to the default branch (main) before creating the mission worktree —
    // mirrors the real scenario: default branch is empty, the scaffold
    // lives only on base_branch.
    quiet_command(git_binary()).args(["checkout", "-"]).current_dir(&repo_path).output().expect("git checkout back");

    let branch = "agent/M-continue-scaffold".to_string();
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, Some(&base_branch), None)
        .expect("agent_create_worktree_inner with a valid base_branch must succeed");

    let scaffold_in_worktree = std::path::Path::new(&wt_path).join("SCAFFOLD.md");
    assert!(
        scaffold_in_worktree.exists(),
        "worktree created with base_branch={:?} must contain the base branch's SCAFFOLD.md, got dir listing: {:?}",
        base_branch,
        std::fs::read_dir(&wt_path).map(|it| it.filter_map(|e| e.ok().map(|e| e.file_name())).collect::<Vec<_>>())
    );
}

/// Honest failure (the exact bug this feature fixes): a base_branch that
/// does not exist must FAIL the call with a reason naming the branch —
/// never silently create the worktree off HEAD instead.
#[test]
fn agent_create_worktree_with_nonexistent_base_branch_fails_explicitly() {
    use super::agent_create_worktree_inner;

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    let branch = "agent/M-continue-missing-scaffold".to_string();
    let missing_base = "agent/does-not-exist-anywhere";
    let result = agent_create_worktree_inner(&repo_path, &branch, Some(missing_base), None);

    assert!(
        result.is_err(),
        "a nonexistent base_branch must fail the call, got Ok: {:?}",
        result
    );
    let err = result.unwrap_err();
    assert!(
        err.contains(missing_base),
        "failure reason must name the missing base branch, got: {:?}",
        err
    );

    // No worktree must have been created at all — no silent fallback to HEAD.
    let wt_dir = std::path::Path::new(&repo_path).join(".lazy").join("worktrees");
    if wt_dir.exists() {
        let leaked: Vec<_> = std::fs::read_dir(&wt_dir)
            .expect("read worktrees dir")
            .filter_map(|e| e.ok())
            .collect();
        assert!(
            leaked.is_empty(),
            "no worktree directory must be created when base_branch does not exist, found: {:?}",
            leaked.iter().map(|e| e.file_name()).collect::<Vec<_>>()
        );
    }
}

/// Fan-in dependency merge, success case: a step with two upstream
/// branches must see BOTH branches' files in its worktree — never just
/// the base_branch's, silently dropping the other dependency.
#[test]
fn agent_create_worktree_merges_extra_branch_into_worktree() {
    use super::agent_create_worktree_inner;

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    // Dependency A: a branch off HEAD adding A.md.
    let branch_a = "agent/dep-a".to_string();
    quiet_command(git_binary()).args(["checkout", "-b", &branch_a]).current_dir(&repo_path).output().expect("checkout dep-a");
    std::fs::write(std::path::Path::new(&repo_path).join("A.md"), "# A\n").expect("write A.md");
    quiet_command(git_binary()).args(["add", "A.md"]).current_dir(&repo_path).output().expect("add A.md");
    quiet_command(git_binary()).args(["commit", "-m", "dep-a"]).current_dir(&repo_path).output().expect("commit dep-a");

    // Dependency B: a SIBLING branch off the same HEAD adding B.md
    // (independent file, no conflict with A.md).
    quiet_command(git_binary()).args(["checkout", "-"]).current_dir(&repo_path).output().expect("back to main");
    let branch_b = "agent/dep-b".to_string();
    quiet_command(git_binary()).args(["checkout", "-b", &branch_b]).current_dir(&repo_path).output().expect("checkout dep-b");
    std::fs::write(std::path::Path::new(&repo_path).join("B.md"), "# B\n").expect("write B.md");
    quiet_command(git_binary()).args(["add", "B.md"]).current_dir(&repo_path).output().expect("add B.md");
    quiet_command(git_binary()).args(["commit", "-m", "dep-b"]).current_dir(&repo_path).output().expect("commit dep-b");

    quiet_command(git_binary()).args(["checkout", "main"]).current_dir(&repo_path).output().expect("back to main");

    let branch = "agent/M-join-a-b".to_string();
    let merge_branches = vec![branch_b.clone()];
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, Some(&branch_a), Some(&merge_branches))
        .expect("agent_create_worktree_inner with a valid merge_branches entry must succeed");

    assert!(
        std::path::Path::new(&wt_path).join("A.md").exists(),
        "worktree must contain base_branch's A.md"
    );
    assert!(
        std::path::Path::new(&wt_path).join("B.md").exists(),
        "worktree must contain the MERGED dependency's B.md — a fan-in dependency must never be silently dropped"
    );
}

/// Honest failure: a merge_branches entry that does not exist must fail
/// the whole call with a reason naming it — never silently create the
/// worktree from base_branch alone and drop the missing dependency.
#[test]
fn agent_create_worktree_with_nonexistent_merge_branch_fails_explicitly() {
    use super::agent_create_worktree_inner;

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    let branch = "agent/M-join-missing".to_string();
    let missing_merge = "agent/does-not-exist-anywhere".to_string();
    let merge_branches = vec![missing_merge.clone()];
    let result = agent_create_worktree_inner(&repo_path, &branch, None, Some(&merge_branches));

    assert!(result.is_err(), "a nonexistent merge branch must fail the call, got Ok: {:?}", result);
    let err = result.unwrap_err();
    assert!(
        err.contains(&missing_merge),
        "failure reason must name the missing merge branch, got: {:?}",
        err
    );

    let wt_dir = std::path::Path::new(&repo_path).join(".lazy").join("worktrees");
    if wt_dir.exists() {
        let leaked: Vec<_> = std::fs::read_dir(&wt_dir).expect("read worktrees dir").filter_map(|e| e.ok()).collect();
        assert!(
            leaked.is_empty(),
            "no worktree directory must be created when a merge branch does not exist, found: {:?}",
            leaked.iter().map(|e| e.file_name()).collect::<Vec<_>>()
        );
    }
}

/// A genuine merge conflict between two dependency branches must fail
/// explicitly (naming the conflicting branch) and leave NO half-merged
/// worktree behind — never start the mission on a broken tree.
#[test]
fn agent_create_worktree_merge_conflict_fails_explicitly_and_cleans_up() {
    use super::agent_create_worktree_inner;

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    // Dependency A: overwrites README.md one way.
    let branch_a = "agent/conflict-a".to_string();
    quiet_command(git_binary()).args(["checkout", "-b", &branch_a]).current_dir(&repo_path).output().expect("checkout conflict-a");
    std::fs::write(std::path::Path::new(&repo_path).join("README.md"), "# Version A\n").expect("write README A");
    quiet_command(git_binary()).args(["commit", "-am", "conflict-a"]).current_dir(&repo_path).output().expect("commit conflict-a");

    // Dependency B: overwrites the SAME line of README.md a different way.
    quiet_command(git_binary()).args(["checkout", "-"]).current_dir(&repo_path).output().expect("back to main");
    let branch_b = "agent/conflict-b".to_string();
    quiet_command(git_binary()).args(["checkout", "-b", &branch_b]).current_dir(&repo_path).output().expect("checkout conflict-b");
    std::fs::write(std::path::Path::new(&repo_path).join("README.md"), "# Version B\n").expect("write README B");
    quiet_command(git_binary()).args(["commit", "-am", "conflict-b"]).current_dir(&repo_path).output().expect("commit conflict-b");

    quiet_command(git_binary()).args(["checkout", "main"]).current_dir(&repo_path).output().expect("back to main");

    let branch = "agent/M-join-conflict".to_string();
    let merge_branches = vec![branch_b.clone()];
    let result = agent_create_worktree_inner(&repo_path, &branch, Some(&branch_a), Some(&merge_branches));

    assert!(result.is_err(), "a genuine merge conflict must fail the call, got Ok: {:?}", result);
    let err = result.unwrap_err();
    assert!(
        err.contains(&branch_b),
        "failure reason must name the conflicting branch, got: {:?}",
        err
    );

    let wt_dir = std::path::Path::new(&repo_path).join(".lazy").join("worktrees");
    if wt_dir.exists() {
        let leaked: Vec<_> = std::fs::read_dir(&wt_dir).expect("read worktrees dir").filter_map(|e| e.ok()).collect();
        assert!(
            leaked.is_empty(),
            "no worktree directory must survive a merge conflict, found: {:?}",
            leaked.iter().map(|e| e.file_name()).collect::<Vec<_>>()
        );
    }
}

/// Verify the discard path: worktree removed without merging.
#[test]
fn agent_worktree_discard_path() {
    use super::{agent_create_worktree_inner, agent_discard_worktree_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    let branch = "agent/discard-test".to_string();
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, None, None)
        .expect("agent_create_worktree failed");

    // Write a file (should NOT appear in main repo after discard)
    let notes_path = std::path::Path::new(&wt_path).join("DISCARD_ME.md");
    std::fs::write(&notes_path, "should not be merged\n").expect("write");

    // Discard
    let discard_result = agent_discard_worktree_inner(
        &repo_path,
        &wt_path,
        &branch,
    );
    assert!(
        discard_result.is_ok(),
        "agent_discard_worktree failed: {:?}",
        discard_result
    );

    // Worktree dir must be gone
    assert!(
        !std::path::Path::new(&wt_path).exists(),
        "Worktree must be removed after discard: {}",
        wt_path
    );

    // File must NOT exist in main repo
    let not_merged = std::path::Path::new(&repo_path).join("DISCARD_ME.md");
    assert!(
        !not_merged.exists(),
        "DISCARD_ME.md must NOT be in main repo after discard"
    );

    eprintln!("agent_worktree_discard_path PASSED");
}

// ── Windows verbatim-path regression coverage ──
//
// The two tests above (agent_worktree_full_lifecycle,
// agent_worktree_discard_path) pass repo_path straight from
// `TempDir::path()`, which on Windows is NEVER `\\?\`-prefixed — while
// get_project_root's canonicalize() output (what the frontend always
// passes as repoPath in the real app) IS verbatim-prefixed. These two
// tests exercise that exact shape end to end as defense-in-depth (see
// worktree_cleanup.rs's module doc comment for what real-app QA's leak
// actually traced back to — a Windows file-lock race, not this).

/// Defect #1 repro: after a SUCCESSFUL merge with a verbatim (canonicalized)
/// repo_path, the worktree directory AND its branch must both be gone.
#[test]
fn agent_worktree_merge_removes_worktree_and_branch_with_verbatim_repo_path() {
    use super::{agent_create_worktree_inner, agent_merge_worktree_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let plain_root = setup_git_repo(&repo_dir);
    let verbatim_root = std::path::Path::new(&plain_root)
        .canonicalize()
        .expect("canonicalize")
        .to_string_lossy()
        .to_string();
    #[cfg(target_os = "windows")]
    assert!(
        verbatim_root.starts_with(r"\\?\"),
        "sanity: canonicalize() must yield a verbatim path on Windows, got {}",
        verbatim_root
    );

    let branch = "agent/merge-verbatim-test".to_string();
    let wt_path = agent_create_worktree_inner(&verbatim_root, &branch, None, None)
        .expect("agent_create_worktree failed (verbatim repo_path)");

    let notes_path = std::path::Path::new(&wt_path).join("VERBATIM_NOTES.md");
    std::fs::write(&notes_path, "written under a verbatim repo_path\n").expect("write");

    let merge_result = agent_merge_worktree_inner(&verbatim_root, &branch, None);
    assert!(
        merge_result.is_ok(),
        "agent_merge_worktree failed with a verbatim repo_path: {:?}",
        merge_result
    );
    let merge_sha = merge_result.expect("checked above");
    assert_eq!(
        merge_sha.len(), 40,
        "merge sha should be a full 40-char hex commit sha even with a verbatim repo_path, got: {:?}", merge_sha
    );

    assert!(
        std::path::Path::new(&plain_root).join("VERBATIM_NOTES.md").exists(),
        "VERBATIM_NOTES.md must be merged into the main repo"
    );
    assert!(
        !std::path::Path::new(&wt_path).exists(),
        "worktree directory must be removed after merge even with a verbatim repo_path: {}",
        wt_path
    );

    let branches = quiet_command(git_binary())
        .args(["branch", "--list", &branch])
        .current_dir(&plain_root)
        .output()
        .expect("git branch --list");
    assert!(
        String::from_utf8_lossy(&branches.stdout).trim().is_empty(),
        "branch '{}' must be deleted after a successful merge, got: {:?}",
        branch,
        String::from_utf8_lossy(&branches.stdout)
    );

    eprintln!("agent_worktree_merge_removes_worktree_and_branch_with_verbatim_repo_path PASSED");
}

/// os error 267 repro, TOP-LEVEL merge variant (2026-08-05 follow-up):
/// the test above (`..._with_verbatim_repo_path`) only exercises a
/// CLEAN verbatim `repo_path` (no stray '/'). This test targets Step 1a's
/// `git add` specifically — the exact call the prod error message names
/// ("agent_merge_worktree: git add failed: ... os error 267") — with a
/// `repo_path` that is BOTH verbatim AND mixed-separator, `merge_into_dir`
/// left `None` (a plain top-level approve, no orchestrator fan-out
/// involved at all). Closes the one remaining untested shape: Step 1a's
/// `wt_cwd` is built by `Path::join`ing `repo_path` itself — this proves
/// that join-then-normalize survives a mixed-separator INPUT to
/// `agent_merge_worktree_inner`, not just a mixed-separator
/// `merge_into_dir` computed independently.
#[test]
fn agent_merge_worktree_survives_a_mixed_separator_verbatim_repo_path_top_level() {
    use super::{agent_create_worktree_inner, agent_merge_worktree_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let plain_root = setup_git_repo(&repo_dir);
    let verbatim_root = std::path::Path::new(&plain_root)
        .canonicalize()
        .expect("canonicalize")
        .to_string_lossy()
        .to_string();
    #[cfg(target_os = "windows")]
    assert!(
        verbatim_root.starts_with(r"\\?\"),
        "sanity: canonicalize() must yield a verbatim path on Windows, got {}",
        verbatim_root
    );

    // Mix in a stray '/' — the minimal repro (a single stray '/' inside
    // an otherwise verbatim, backslash-only string disables Win32's
    // separator translation for the WHOLE string).
    let mixed_repo_path = {
        let mut s = verbatim_root.clone();
        let pos = s.rfind('\\').expect("verbatim root must contain at least one backslash");
        s.replace_range(pos..pos + 1, "/");
        s
    };
    assert!(
        mixed_repo_path.contains('/'),
        "test precondition: mixed_repo_path must contain a stray '/', got {}",
        mixed_repo_path
    );

    // Worktree creation itself already goes through agent_create_worktree_inner
    // with the CLEAN verbatim_root (creation is not what's under test here —
    // only the merge's own repo_path handling is), so the worktree physically
    // exists at the location agent_merge_worktree_inner will independently
    // recompute from mixed_repo_path.
    let branch = "agent/merge-mixed-repo-path-top-level".to_string();
    let wt_path = agent_create_worktree_inner(&verbatim_root, &branch, None, None)
        .expect("agent_create_worktree failed (verbatim repo_path)");
    std::fs::write(
        std::path::Path::new(&wt_path).join("TOP_LEVEL_MIXED.md"),
        "# top-level mixed-separator repo_path\n",
    )
    .expect("write deliverable");

    // THE call: repo_path itself (not merge_into_dir) is mixed-separator
    // verbatim, merge_into_dir is None (plain top-level approve).
    let merge_result = agent_merge_worktree_inner(&mixed_repo_path, &branch, None);
    assert!(
        merge_result.is_ok(),
        "agent_merge_worktree_inner must survive a mixed-separator verbatim repo_path on a top-level merge (os error 267 regression), got: {:?}",
        merge_result
    );

    assert!(
        std::path::Path::new(&plain_root).join("TOP_LEVEL_MIXED.md").exists(),
        "deliverable must be merged into the main repo even with a mixed-separator verbatim repo_path"
    );

    eprintln!("agent_merge_worktree_survives_a_mixed_separator_verbatim_repo_path_top_level PASSED");
}

/// os error 267 repro (2026-08-05, PROD incident — see
/// normalize_for_git's doc comment, util.rs, and this file's own
/// 2026-08-05 comments on agent_merge_worktree_inner/git_revert_merge_inner
/// for the full root-cause). `merge_into_dir` is exactly what
/// runtime.ts's `mergeWorktree` (src/lib/agents/runtime.ts) passes
/// straight through to the `agent_merge_worktree` Tauri invoke with NO
/// normalization — unlike `repoPath`, which QA B11 already normalizes on
/// the TypeScript side (paths.ts's normalizeRepoPathForGit). A verbatim
/// (`\\?\`-prefixed) `merge_into_dir` carrying even one stray '/' (mixed
/// separators — the orchestrator fan-out's parent worktree path, joined
/// upstream with a hardcoded '/' somewhere in the call chain) used to
/// fail `Command::current_dir` outright with "os error 267"
/// (ERROR_DIRECTORY_NAME_INVALID) before agent_merge_worktree_inner
/// started routing every git subprocess's `current_dir` through
/// `normalize_for_git`. This is the exact "some merges fail, others
/// pass" shape reported in prod: a plain top-level merge
/// (`merge_into_dir` = None, exercised by the verbatim `repo_path` test
/// above) was already fine; a fan-in merge with a mixed-separator
/// `merge_into_dir` was not.
#[test]
fn agent_merge_worktree_survives_a_mixed_separator_verbatim_merge_into_dir() {
    use super::{agent_create_worktree_inner, agent_merge_worktree_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let plain_root = setup_git_repo(&repo_dir);
    let verbatim_root = std::path::Path::new(&plain_root)
        .canonicalize()
        .expect("canonicalize")
        .to_string_lossy()
        .to_string();

    // Parent mission worktree — its path is what a real orchestrator
    // fan-out passes as `merge_into_dir` (see agent_merge_worktree's doc
    // comment above and runtime.ts's Step E).
    let parent_branch = "agent/M-parent-267".to_string();
    let parent_wt_path = agent_create_worktree_inner(&verbatim_root, &parent_branch, None, None)
        .expect("parent agent_create_worktree failed");
    #[cfg(target_os = "windows")]
    assert!(
        parent_wt_path.starts_with(r"\\?\"),
        "sanity: parent worktree path must be verbatim-prefixed on Windows, got {}",
        parent_wt_path
    );

    // Reproduce runtime.ts's un-normalized `mergeIntoDir` shape: the
    // minimal repro is a SINGLE stray '/' anywhere in an otherwise
    // verbatim, backslash-only string — that alone disables Win32's
    // separator translation for the WHOLE string.
    let mixed_merge_into_dir = {
        let mut s = parent_wt_path.clone();
        let pos = s.rfind('\\').expect("worktree path must contain at least one backslash");
        s.replace_range(pos..pos + 1, "/");
        s
    };
    assert!(
        mixed_merge_into_dir.contains('/'),
        "test precondition: mixed_merge_into_dir must contain a stray '/', got {}",
        mixed_merge_into_dir
    );

    // Child role sub-agent worktree, created off the TRUE repo root —
    // same shape as runtime.ts Step E.
    let child_branch = "agent/M-child-267".to_string();
    let child_wt_path = agent_create_worktree_inner(&verbatim_root, &child_branch, None, None)
        .expect("child agent_create_worktree failed");
    std::fs::write(
        std::path::Path::new(&child_wt_path).join("CHILD_WORK.md"),
        "# child work\n",
    )
    .expect("write child deliverable");

    // THE call: repo_path stays the true root, merge_into_dir is the
    // mixed-separator verbatim parent path — this must still succeed.
    let merge_result = agent_merge_worktree_inner(&verbatim_root, &child_branch, Some(&mixed_merge_into_dir));
    assert!(
        merge_result.is_ok(),
        "agent_merge_worktree_inner must survive a mixed-separator verbatim merge_into_dir (os error 267 regression), got: {:?}",
        merge_result
    );

    assert!(
        std::path::Path::new(&parent_wt_path).join("CHILD_WORK.md").exists(),
        "child's work must land in the parent worktree even when merge_into_dir was mixed-separator verbatim"
    );

    eprintln!("agent_merge_worktree_survives_a_mixed_separator_verbatim_merge_into_dir PASSED");
}

/// Defect #2 repro: the discard/stop path must also remove the worktree
/// directory AND its branch when repo_path is verbatim (canonicalized) —
/// same underlying bug as the merge path above, hit through
/// agent_discard_worktree_inner instead.
#[test]
fn agent_worktree_discard_removes_worktree_and_branch_with_verbatim_repo_path() {
    use super::{agent_create_worktree_inner, agent_discard_worktree_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let plain_root = setup_git_repo(&repo_dir);
    let verbatim_root = std::path::Path::new(&plain_root)
        .canonicalize()
        .expect("canonicalize")
        .to_string_lossy()
        .to_string();

    let branch = "agent/discard-verbatim-test".to_string();
    // agent_create_worktree_inner joins off of repo_path, so passing the
    // verbatim root here reproduces the exact real-app shape: the
    // worktree's own path AND the path later passed back to discard
    // (agentsStore.tsx's resolveDiscardWorktreePath, which joins onto
    // get_project_root's own verbatim output) are both verbatim-prefixed.
    let wt_path = agent_create_worktree_inner(&verbatim_root, &branch, None, None)
        .expect("agent_create_worktree failed (verbatim repo_path)");

    let discard_result = agent_discard_worktree_inner(&verbatim_root, &wt_path, &branch);
    assert!(
        discard_result.is_ok(),
        "agent_discard_worktree failed with a verbatim repo_path: {:?}",
        discard_result
    );

    assert!(
        !std::path::Path::new(&wt_path).exists(),
        "worktree must be removed even with a verbatim repo_path: {}",
        wt_path
    );

    let branches = quiet_command(git_binary())
        .args(["branch", "--list", &branch])
        .current_dir(&plain_root)
        .output()
        .expect("git branch --list");
    assert!(
        String::from_utf8_lossy(&branches.stdout).trim().is_empty(),
        "branch '{}' must be deleted after discard, got: {:?}",
        branch,
        String::from_utf8_lossy(&branches.stdout)
    );

    eprintln!("agent_worktree_discard_removes_worktree_and_branch_with_verbatim_repo_path PASSED");
}

/// "Only remove on success" contract: a merge that fails with a real
/// conflict must leave the worktree directory AND its branch fully
/// intact — the user can retry or inspect. Cleanup must never run before
/// merge_out.status.success() is confirmed.
#[test]
fn agent_merge_worktree_never_removes_worktree_on_merge_conflict() {
    use super::{agent_create_worktree_inner, agent_merge_worktree_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    let branch = "agent/conflict-test".to_string();
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, None, None)
        .expect("agent_create_worktree failed");

    // Conflicting edit in the worktree (uncommitted — Step 1 of the merge
    // function commits it onto the worktree's own branch).
    let wt_readme = std::path::Path::new(&wt_path).join("README.md");
    std::fs::write(&wt_readme, "# repo\nagent change\n").expect("write worktree README");

    // Conflicting edit + commit on the main repo's current branch, so the
    // merge in Step 2 hits a real conflict.
    let main_readme = std::path::Path::new(&repo_path).join("README.md");
    std::fs::write(&main_readme, "# repo\nmain change\n").expect("write main README");
    quiet_command(git_binary())
        .args(["add", "README.md"])
        .current_dir(&repo_path)
        .output()
        .expect("git add (main)");
    quiet_command(git_binary())
        .args(["commit", "-m", "main change"])
        .current_dir(&repo_path)
        .output()
        .expect("git commit (main)");

    let merge_result = agent_merge_worktree_inner(&repo_path, &branch, None);
    let err = match &merge_result {
        Err(e) => e.clone(),
        Ok(_) => panic!("expected a conflicting merge to fail, got: {:?}", merge_result),
    };
    assert!(
        err.starts_with("MERGE_CONFLICT:"),
        "conflict error must be tagged MERGE_CONFLICT so the frontend can classify it, got: {}",
        err
    );

    assert!(
        std::path::Path::new(&wt_path).exists(),
        "worktree directory must NOT be removed after a failed merge: {}",
        wt_path
    );

    let branches = quiet_command(git_binary())
        .args(["branch", "--list", &branch])
        .current_dir(&repo_path)
        .output()
        .expect("git branch --list");
    assert!(
        !String::from_utf8_lossy(&branches.stdout).trim().is_empty(),
        "branch '{}' must survive a failed merge",
        branch
    );

    // QA bug fix: the user's own working tree (repo_path) must NEVER be
    // left mid-merge — MERGE_HEAD must be gone (auto-aborted) and there
    // must be no leftover conflict markers/unmerged paths.
    let merge_head_check = quiet_command(git_binary())
        .args(["rev-parse", "-q", "--verify", "MERGE_HEAD"])
        .current_dir(&repo_path)
        .output()
        .expect("git rev-parse MERGE_HEAD check");
    assert!(
        !merge_head_check.status.success(),
        "MERGE_HEAD must be gone after the auto-abort — the repo must never be left mid-merge"
    );

    let status_out = quiet_command(git_binary())
        .args(["status", "--porcelain"])
        .current_dir(&repo_path)
        .output()
        .expect("git status --porcelain");
    let status_text = String::from_utf8_lossy(&status_out.stdout);
    assert!(
        !status_text.contains("UU") && !status_text.contains("AA"),
        "no unmerged paths must remain after the auto-abort, got status: {}",
        status_text
    );

    eprintln!("agent_merge_worktree_never_removes_worktree_on_merge_conflict PASSED");
}

/// Run-11 root-cause regression: `.lazy/`/`.lazybrain/` app
/// infrastructure (brain caches, an OPEN-in-the-live-app fts.sqlite)
/// must never ride along in a mission commit. Before 43fed1f, Step 1a
/// staged with explicit `:(exclude).lazy`/`:(exclude).lazybrain`
/// pathspecs; since 43fed1f it relies on the repo's TRACKED
/// `.gitignore` (present in every real checkout — see the repo root's
/// own `.gitignore`) to skip them instead, because naming already-
/// ignored paths in the pathspec made git abort the whole `add` when a
/// worktree carried a nested `.lazy/`. This fixture commits an
/// equivalent `.gitignore` before creating the worktree, mirroring a
/// real project root. The mission commit must carry the mission's work
/// ONLY, and near-miss names (`.lazyfoo`) must still be committed.
#[test]
fn agent_merge_worktree_excludes_lazy_infra_junk() {
    use super::{agent_create_worktree_inner, agent_merge_worktree_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    // The worktree only skips `.lazy/`/`.lazybrain/` via the repo's
    // TRACKED `.gitignore` (see agent_merge_worktree_inner's Step 1a
    // comment) — every real checkout carries one, so mirror that here
    // instead of leaving this fixture repo without one.
    std::fs::write(
        std::path::Path::new(&repo_path).join(".gitignore"),
        ".lazy/\n.lazybrain/\n",
    )
    .expect("write .gitignore");
    quiet_command(git_binary())
        .args(["add", ".gitignore"])
        .current_dir(&repo_path)
        .output()
        .expect("git add .gitignore");
    quiet_command(git_binary())
        .args(["commit", "-m", "add gitignore"])
        .current_dir(&repo_path)
        .output()
        .expect("git commit .gitignore");

    let branch = "agent/junk-exclusion-test".to_string();
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, None, None)
        .expect("agent_create_worktree failed");

    // Real mission work + infra junk exactly like a live run produces.
    let wt = std::path::Path::new(&wt_path);
    std::fs::write(wt.join("MISSION.md"), "real work\n").expect("write mission file");
    std::fs::create_dir_all(wt.join(".lazybrain").join("brain").join("_cache"))
        .expect("mkdir .lazybrain");
    std::fs::write(wt.join(".lazybrain").join("brain").join(".cache-migrated"), "ts\n")
        .expect("write cache-migrated");
    std::fs::write(wt.join(".lazybrain").join("brain").join("_cache").join("fts.sqlite"), "db\n")
        .expect("write fts.sqlite");
    std::fs::create_dir_all(wt.join(".lazy")).expect("mkdir .lazy");
    std::fs::write(wt.join(".lazy").join("scratch.json"), "{}\n").expect("write .lazy junk");
    // Component-boundary near-miss: NOT infra, must be committed.
    std::fs::write(wt.join(".lazyfoo"), "not infra\n").expect("write .lazyfoo");

    let merge_sha = agent_merge_worktree_inner(&repo_path, &branch, None)
        .expect("agent_merge_worktree failed");
    assert_eq!(merge_sha.len(), 40, "sanity: merge sha expected, got {:?}", merge_sha);

    // The merged tree carries the mission's files, never the junk.
    let tree_out = quiet_command(git_binary())
        .args(["ls-tree", "-r", "--name-only", "HEAD"])
        .current_dir(&repo_path)
        .output()
        .expect("git ls-tree");
    let tree = String::from_utf8_lossy(&tree_out.stdout).to_string();
    assert!(tree.contains("MISSION.md"), "mission file must be merged, tree: {tree}");
    assert!(tree.contains(".lazyfoo"), ".lazyfoo (near-miss name) must be merged, tree: {tree}");
    assert!(
        !tree.contains(".lazybrain/"),
        ".lazybrain/ junk must never reach the merged tree, tree: {tree}"
    );
    assert!(
        !tree.contains(".lazy/"),
        ".lazy/ junk must never reach the merged tree, tree: {tree}"
    );

    eprintln!("agent_merge_worktree_excludes_lazy_infra_junk PASSED");
}

/// Idempotence at the command layer: discarding an already-discarded
/// worktree must be a safe no-op (Ok), not an error — this is the
/// exact scenario agentsStore.tsx's stopMission creates (its direct
/// cleanup call can race runMission's own independent cleanup path).
#[test]
fn agent_discard_worktree_twice_is_idempotent() {
    use super::{agent_create_worktree_inner, agent_discard_worktree_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);
    let branch = "agent/double-discard-test".to_string();
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, None, None)
        .expect("agent_create_worktree failed");

    let first = agent_discard_worktree_inner(&repo_path, &wt_path, &branch);
    assert!(first.is_ok(), "first discard failed: {:?}", first);
    assert!(!std::path::Path::new(&wt_path).exists());

    let second = agent_discard_worktree_inner(&repo_path, &wt_path, &branch);
    assert!(
        second.is_ok(),
        "second discard of an already-removed worktree must be Ok (idempotent), got: {:?}",
        second
    );

    eprintln!("agent_discard_worktree_twice_is_idempotent PASSED");
}

// ── git_revert_merge (T1.7 — "Revert mission", spec §8 merged case) ──

/// Happy path: merging a worktree branch, then reverting that merge,
/// must restore the pre-merge tree (the file the mission added is gone
/// again) and land a real revert commit at HEAD.
#[test]
fn revert_merge_restores_tree() {
    use super::{agent_create_worktree_inner, agent_merge_worktree_inner, git_revert_merge_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    let branch = "agent/revert-test".to_string();
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, None, None)
        .expect("agent_create_worktree failed");

    let notes_path = std::path::Path::new(&wt_path).join("REVERT_ME.md");
    std::fs::write(&notes_path, "created by the mission\n").expect("write");

    let merge_sha = agent_merge_worktree_inner(&repo_path, &branch, None)
        .expect("agent_merge_worktree failed");
    assert_eq!(merge_sha.len(), 40, "sanity: merge sha should be a full 40-char hex sha");

    let merged_file = std::path::Path::new(&repo_path).join("REVERT_ME.md");
    assert!(merged_file.exists(), "sanity: file must exist after merge, before revert");

    let revert_sha = git_revert_merge_inner(&repo_path, &merge_sha)
        .expect("git_revert_merge failed");
    assert_ne!(revert_sha, merge_sha, "the revert commit must be a NEW commit, not the merge commit itself");
    assert_eq!(revert_sha.len(), 40, "revert sha should be a full 40-char hex commit sha, got: {:?}", revert_sha);

    assert!(
        !merged_file.exists(),
        "REVERT_ME.md must be gone after reverting the merge that introduced it"
    );

    // The revert commit must actually be HEAD now (real history, not a
    // dry-run / no-op).
    let log_out = quiet_command(git_binary())
        .args(["log", "--format=%H", "-n", "1"])
        .current_dir(&repo_path)
        .output()
        .expect("git log");
    let head_sha = String::from_utf8_lossy(&log_out.stdout).trim().to_string();
    assert_eq!(
        head_sha, revert_sha,
        "HEAD after revert must equal the revert commit sha (real history, not a no-op)"
    );

    eprintln!("revert_merge_restores_tree PASSED");
}

/// Unrelated uncommitted files must NOT block a revert (run-11 evidence:
/// the app itself drops an untracked `.gitignore` into every project
/// root, and users routinely have unrelated edits open — the old blanket
/// `git status --porcelain` refusal made revert permanently unusable in
/// any real project). git's own guard still protects the paths the
/// revert touches — see revert_merge_refuses_overlapping_dirty_file.
#[test]
fn revert_merge_allows_unrelated_dirty_files() {
    use super::{agent_create_worktree_inner, agent_merge_worktree_inner, git_revert_merge_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    // A second tracked file so the dirty edit below is UNRELATED to the
    // mission's own file (F.md).
    std::fs::write(std::path::Path::new(&repo_path).join("other.md"), "tracked\n")
        .expect("write other.md");
    quiet_command(git_binary())
        .args(["add", "other.md"])
        .current_dir(&repo_path)
        .output()
        .expect("git add other.md");
    quiet_command(git_binary())
        .args(["commit", "-m", "add other.md"])
        .current_dir(&repo_path)
        .output()
        .expect("git commit other.md");

    let branch = "agent/revert-dirty-test".to_string();
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, None, None)
        .expect("agent_create_worktree failed");
    std::fs::write(std::path::Path::new(&wt_path).join("F.md"), "content\n").expect("write");
    let merge_sha = agent_merge_worktree_inner(&repo_path, &branch, None)
        .expect("agent_merge_worktree failed");

    // Unrelated dirt AFTER the merge landed: one modified tracked file +
    // one untracked file (the exact shape a real project root has).
    std::fs::write(std::path::Path::new(&repo_path).join("other.md"), "tracked but edited\n")
        .expect("dirty other.md");
    std::fs::write(std::path::Path::new(&repo_path).join("UNCOMMITTED.md"), "stray\n")
        .expect("write untracked file");

    let revert_sha = git_revert_merge_inner(&repo_path, &merge_sha)
        .expect("revert must succeed despite unrelated dirty/untracked files");
    assert_eq!(revert_sha.len(), 40, "revert sha should be a full sha, got {:?}", revert_sha);

    // The mission's file is reverted away; the user's own dirt is intact.
    assert!(
        !std::path::Path::new(&repo_path).join("F.md").exists(),
        "F.md must be gone after the revert"
    );
    let other = std::fs::read_to_string(std::path::Path::new(&repo_path).join("other.md"))
        .expect("read other.md");
    assert_eq!(other, "tracked but edited\n", "unrelated dirty edit must survive the revert untouched");
    assert!(
        std::path::Path::new(&repo_path).join("UNCOMMITTED.md").exists(),
        "unrelated untracked file must survive the revert untouched"
    );

    eprintln!("revert_merge_allows_unrelated_dirty_files PASSED");
}

/// Uncommitted changes ON A PATH THE REVERT TOUCHES must still refuse —
/// that protection now comes from `git revert` itself (surfaced as this
/// command's Err) instead of the old blanket pre-check, and the repo
/// must be left clean (no mid-revert state), with the dirty edit intact.
#[test]
fn revert_merge_refuses_overlapping_dirty_file() {
    use super::{agent_create_worktree_inner, agent_merge_worktree_inner, git_revert_merge_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    let branch = "agent/revert-overlap-test".to_string();
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, None, None)
        .expect("agent_create_worktree failed");
    std::fs::write(std::path::Path::new(&wt_path).join("F.md"), "content\n").expect("write");
    let merge_sha = agent_merge_worktree_inner(&repo_path, &branch, None)
        .expect("agent_merge_worktree failed");

    // Dirty THE FILE THE REVERT MUST DELETE — git itself must refuse.
    std::fs::write(std::path::Path::new(&repo_path).join("F.md"), "user edited the merged file\n")
        .expect("dirty F.md");

    let result = git_revert_merge_inner(&repo_path, &merge_sha);
    assert!(result.is_err(), "expected git to refuse reverting over a dirty overlapping file");

    // The user's edit survives, and no revert is left in progress.
    let f = std::fs::read_to_string(std::path::Path::new(&repo_path).join("F.md"))
        .expect("read F.md");
    assert_eq!(f, "user edited the merged file\n", "the overlapping dirty edit must be untouched");
    assert!(
        !std::path::Path::new(&repo_path).join(".git").join("REVERT_HEAD").exists(),
        "no revert may be left in progress after the refusal"
    );

    eprintln!("revert_merge_refuses_overlapping_dirty_file PASSED");
}

/// A plain (non-merge) commit sha must be rejected with a clear,
/// purpose-specific error rather than git's own generic "mainline was
/// not specified" message.
#[test]
fn revert_rejects_non_merge_sha() {
    use super::git_revert_merge_inner;

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    // HEAD (the seed commit from setup_git_repo) is a plain, non-merge commit.
    let head_out = quiet_command(git_binary())
        .args(["rev-parse", "HEAD"])
        .current_dir(&repo_path)
        .output()
        .expect("git rev-parse HEAD");
    let head_sha = String::from_utf8_lossy(&head_out.stdout).trim().to_string();

    let result = git_revert_merge_inner(&repo_path, &head_sha);
    assert!(result.is_err(), "expected a plain (non-merge) commit to be rejected");
    let err = result.unwrap_err().to_lowercase();
    assert!(
        err.contains("not a merge"),
        "error should clearly say it is not a merge commit, got: {:?}", err
    );

    eprintln!("revert_rejects_non_merge_sha PASSED");
}

/// A revert that conflicts must leave the repository clean (revert
/// aborted) instead of stuck mid-conflict — this command runs directly
/// against the caller's real repo (unlike a failed agent_merge_worktree,
/// which intentionally preserves a disposable worktree/branch for
/// retry), so leaving a conflict unresolved would strand the actual
/// project tree.
#[test]
fn revert_merge_conflict_aborts_cleanly() {
    use super::{agent_create_worktree_inner, agent_merge_worktree_inner, git_revert_merge_inner};

    let repo_dir = TempDir::new().expect("TempDir");
    let repo_path = setup_git_repo(&repo_dir);

    let branch = "agent/revert-conflict-test".to_string();
    let wt_path = agent_create_worktree_inner(&repo_path, &branch, None, None)
        .expect("agent_create_worktree failed");
    // Mission edits the seed file (not just adds a new one) so a LATER
    // main-branch edit to the same lines will conflict with the revert.
    std::fs::write(std::path::Path::new(&wt_path).join("README.md"), "# Lazy test repo\nmission line\n")
        .expect("write worktree README");

    let merge_sha = agent_merge_worktree_inner(&repo_path, &branch, None)
        .expect("agent_merge_worktree failed");

    // A further commit on top of the merge, touching the SAME line the
    // revert would need to remove — guarantees a real conflict.
    std::fs::write(std::path::Path::new(&repo_path).join("README.md"), "# Lazy test repo\nmission line edited further\n")
        .expect("write post-merge README edit");
    quiet_command(git_binary())
        .args(["add", "README.md"])
        .current_dir(&repo_path)
        .output()
        .expect("git add (post-merge edit)");
    quiet_command(git_binary())
        .args(["commit", "-m", "further edit on top of the merge"])
        .current_dir(&repo_path)
        .output()
        .expect("git commit (post-merge edit)");

    let head_before = quiet_command(git_binary())
        .args(["rev-parse", "HEAD"])
        .current_dir(&repo_path)
        .output()
        .expect("git rev-parse HEAD (before)");
    let head_before_sha = String::from_utf8_lossy(&head_before.stdout).trim().to_string();

    let result = git_revert_merge_inner(&repo_path, &merge_sha);
    assert!(result.is_err(), "expected the revert to conflict and fail, got: {:?}", result);

    // The repo must be clean again (revert aborted), not left mid-conflict.
    let status_out = quiet_command(git_binary())
        .args(["status", "--porcelain"])
        .current_dir(&repo_path)
        .output()
        .expect("git status");
    assert!(
        String::from_utf8_lossy(&status_out.stdout).trim().is_empty(),
        "working tree must be clean after a failed revert is aborted"
    );

    // HEAD must be unchanged — no partial revert commit left behind.
    let head_after = quiet_command(git_binary())
        .args(["rev-parse", "HEAD"])
        .current_dir(&repo_path)
        .output()
        .expect("git rev-parse HEAD (after)");
    let head_after_sha = String::from_utf8_lossy(&head_after.stdout).trim().to_string();
    assert_eq!(head_before_sha, head_after_sha, "HEAD must be unchanged after an aborted revert");

    eprintln!("revert_merge_conflict_aborts_cleanly PASSED");
}
